---
k3s_version: v1.29.2+k3s1
# this is the user that has ssh access to these machines
ansible_user: "{{ remote_user }}"
systemd_dir: /etc/systemd/system

# Set your timezone
system_timezone: "America/Denver"

# interface which will be used for flannel
flannel_iface: "enp1s0f0"

# enable cilium bgp control plane for lb services and pod cidrs. disables metallb.
cilium_bgp: false

# apiserver_endpoint is virtual ip-address which will be configured on each master
apiserver_endpoint: "192.168.0.201" # CHANGED

# k3s_token is required  masters can talk together securely
# this token should be alpha numeric only
# omitted as k3s_token is stored in ./inventory/shannon/group_vars/vault.yml
# k3s_token: "some-SUPER-DEDEUPER-secret-password"


# The IP on which the node is reachable in the cluster.
k3s_node_ip: "{{ ansible_facts[(cilium_iface | default(calico_iface | default(flannel_iface)))]['ipv4']['address'] }}"
# k3s_node_ip: "192.168.0.201" # CHANGED

# Disable the taint manually by setting: k3s_master_taint = false
k3s_master_taint: "{{ true if groups['node'] | default([]) | length >= 1 else false }}"

# these arguments are recommended for servers as well as agents:
extra_args: >-
  {{ '--flannel-iface=' + flannel_iface if calico_iface is not defined and cilium_iface is not defined else '' }}
  --node-ip={{ k3s_node_ip }}

# change these to your liking, the only required are: --disable servicelb, --tls-san {{ apiserver_endpoint }}
# the contents of the if block is also required if using calico or cilium
extra_server_args: >-
  {{ extra_args }}
  {{ '--node-taint node-role.kubernetes.io/master=true:NoSchedule' if k3s_master_taint else '' }}
  {% if calico_iface is defined or cilium_iface is defined %}
  --flannel-backend=none
  --disable-network-policy
  --cluster-cidr={{ cluster_cidr | default('10.52.0.0/16') }}
  {% endif %}
  --tls-san {{ apiserver_endpoint }}
  --disable servicelb
  --disable traefik

extra_agent_args: >-
  {{ extra_args }}

# image tag for kube-vip
kube_vip_tag_version: "v0.7.2"

# metallb type frr or native
metal_lb_type: "native"

# metallb mode layer2 or bgp
metal_lb_mode: "layer2"

# image tag for metal lb
metal_lb_speaker_tag_version: "v0.14.3"
metal_lb_controller_tag_version: "v0.14.3"

# metallb ip range for load balancer
# router dhcp reservation range: 192.168.0.2 - 192.168.0.128
metal_lb_ip_range: "192.168.0.130-192.168.0.140"

proxmox_lxc_configure: false
# the user that you would use to ssh into the host, for example if you run ssh some-user@my-proxmox-host,
# set this value to some-user
proxmox_lxc_ssh_user: root
# the unique proxmox ids for all of the containers in the cluster, both worker and master nodes
proxmox_lxc_ct_ids:
  - 200
  - 201
  - 202
  - 203
  - 204

#
custom_registries: false